# UI
mode: auto

post_card:
  opacity: 0.6

# ç½‘ç«™åŸºæœ¬é…ç½®
avatar:
  enable: true
  url: /me.webp
  opacity: 1
  status:
    enable: true
    emoji: ğŸ‘€
    message: åœ¨çœ‹ä»€ä¹ˆå‘¢ï¼Ÿæœ‰å¿…è¦è¯´å—ï¼ˆ

favicon: /favicon.ico


# å…¬å‘Š
notice:
  enable: true
  content: æˆ–è®¸ï¼Ÿä¸çŸ¥é“ä»€ä¹ˆæ—¶å€™å°±æ²¡äº†ï¼ˆ

# èµèµç 
reward:
  enable: false
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: æ”¯ä»˜å®
      path: 
      color: "#00A3EE"
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: 
      color: "#12B7F5"
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: 
      color: "#2DC100"
      icon: ri:wechat-pay-line

# è¯„è®º
comment:
  candidates:
    - waline
    # - giscus
  tips:
    - ä¸€èˆ¬æ¥è¯´éƒ½æ˜¯å¼ºåˆ¶ä½ å†™é‚®ç®±åœ°å€ä»¥ä¾¿äºæ”¶åˆ°å›å¤é€šçŸ¥
    - é‚®ä»¶é€šçŸ¥çš„è¯ï¼Œæœ‰æ—¶å€™ä¼šè¢«ä¸¢åˆ°åƒåœ¾ç®±é‚£ï¼Œé‚£æˆ‘ä¹Ÿæ²¡åŠæ³•äº†

waline:
  enable: true
  serverURL: https://pl-lijiakaijun.vercel.app
  visitor: true
  comment: true
  login: 'disable'
  emoji:
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://pic.lijiakaijun.cyou/emote/reci
    - https://pic.lijiakaijun.cyou/emote/kano
    - https://pic.lijiakaijun.cyou/emote/qinai
    - https://pic.lijiakaijun.cyou/emote/orange
    - https://pic.lijiakaijun.cyou/emote/mea
  locale:
    placeholder: æƒ³è¯´ç‚¹ä»€ä¹ˆå‘¢...
  requiredMeta: ['nick', 'mail']

# é¡µå¤´ä¸é¡µå°¾

banner:
  enable: true
  title: 
    - lijia
    - kaijun
  border: true
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

bg_image:
  enable: true
  url: https://pic.lijiakaijun.cyou/light.webp
  dark: https://pic.lijiakaijun.cyou/dark.webp

footer:
  live_time:
    enable: true
    prefix: ä¸ç»æ„é—´ï¼Œæœ¬ç«™å·²ç»è¿è¡Œäº†
    suffix: (â—'â—¡'â—)
    start_time: "2019-09-14T10:08:00"
  custom_text: <a href="https://icp.gov.moe" target="_blank">èŒICPå¤‡</a><a href="https://icp.gov.moe/?keyword=20215956" target="_blank"> 20215956å·</a>

# æœç´¢ç›¸å…³

engine_search:
  enable: false

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia
algolia_search:
  enable: false
  # ...

local_search:
  enable: true

# ç½‘ç«™ç»Ÿè®¡/å¹¿å‘Šç›¸å…³

google_analytics:
  enable: true
  id: G-WVHRB2RVB6

google_adsense:
  enable: false
  client: 

baidu_push: false

google_tagmanager:
  enable: false
  id: 


# ç¼–è¾‘

post_edit:
  enable: true
  url: https://github.com/lijiajunljj/lijiakaijun-blog/tree/main/source/

girls:
  enable: true

# é¡µé¢é“¾æ¥ã€å¯¼èˆª

pages:
  - name: å‹~é“¾~
    url: /links
    icon: ri:genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls
    icon: ri:women-line
    color: hotpink

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives
  custom:
    title: ç•™è¨€æ¿
    path: /contact
    icon: ri:clipboard-line

cursor:
  enable: true


wordcount:
  enable: true

# ä¸€è¨€

say:
  enable: true
  api: /files/onetext-blog.json
  hitokoto:
    enable: false
    api: https://v1.hitokoto.cn

# ç¤¾äº¤
social:
  - name: ä¸»é¡µ
    link: https://lijiakaijun.cyou
    icon: ri:home-line
    color: "#50D7D2"
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: bilibili
    link: https://space.bilibili.com/480198701
    icon: ri:bilibili-line
    color: "#FF8EB3"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=1509875152
    icon: ri:netease-cloud-music-line
    color: "#C10D0C"
  - name: GitHub
    link: https://github.com/lijiakaijun
    icon: ri:github-line
    color: "#95A4A6"
  - name: Twitter
    link: https://twitter.com/lijia_ver6
    icon: ri:twitter-line
    color: "#1da1f2"
  - name: Telegramé¢‘é“
    link: https://t.me/lijiakaijun
    icon: ri:telegram-line
    color: "#0088CC"
  - name: E-Mail
    link: mailto:wwln@lijiakaijun.cyou
    icon: ri:mail-line
    color: "#8E71C1"

# æ‚é¡¹

mourn:
  enable: false
  days:
    - "2-15"
    - "4-4"

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

# cdn

vendors:
  # ä»¥ '/' ç»“å°¾
  host: 'https://fastly.jsdelivr.net/npm/'