# UI
mode: auto

# ç½‘ç«™åŸºæœ¬é…ç½®

avatar:
  enable: true
  url: /me.webp
  opacity: 1
  status:
    enable: true
    emoji: ğŸ‘€
    message: åœ¨çœ‹ä»€ä¹ˆå‘¢ï¼Ÿæœ‰å¿…è¦è¯´å—ï¼ˆ

favicon: /favicon.ico

pjax:
  enable: true

# å…¬å‘Š

notice:
  enable: true
  content: åŸŸåè¿™å‡ ä¸ªæœˆå¯èƒ½ä¼šæœ‰å˜åŠ¨ï¼Œä½†ç»­æœŸè¿˜æ˜¯ä¼šç»­æœŸçš„ï¼ˆ 

# èµèµç 

reward:
  enable: false
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: æ”¯ä»˜å®
      path: 
      color: "#00A3EE"
      icon: ri:alipay-line
    - name: QQ æ”¯ä»˜
      path: 
      color: "#12B7F5"
      icon: ri:qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: 
      color: "#2DC100"
      icon: ri:wechat-pay-line

# è¯„è®º

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - ä¸€èˆ¬æ¥è¯´éƒ½æ˜¯å¼ºåˆ¶ä½ å†™é‚®ç®±åœ°å€ä»¥ä¾¿äºæ”¶åˆ°å›å¤é€šçŸ¥
    - æœ‰æ—¶å€™é‚®ä»¶ä¼šè¢«ä¸¢åˆ°åƒåœ¾ç®±é‚£ï¼Œæˆ‘ä¹Ÿæ²¡åŠæ³•äº†

waline:
  enable: true
  serverURL: https://pl-lijiakaijun.vercel.app
  visitor: true
  comment: true
  login: 'disable'
  emoji:
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://pic.lijiakaijun.cyou/emote/reci
    - https://pic.lijiakaijun.cyou/emote/kano
    - https://pic.lijiakaijun.cyou/emote/qinai
    - https://pic.lijiakaijun.cyou/emote/orange
    - https://pic.lijiakaijun.cyou/emote/mea
  dark: 'html[class="sr dark"]'
  locale:
    placeholder: æƒ³è¯´ç‚¹ä»€ä¹ˆå‘¢...
  requiredMeta: ['nick', 'mail']

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: 
  apikey: 

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: YunYouJun/yunyoujun.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

# é¡µå¤´ä¸é¡µå°¾

banner:
  enable: true
  title: 
    - lijia
    - kaijun
  border: true
  go_down:
    enable: true
    icon: ri:arrow-down-s-line

bg_image:
  enable: true
  url: https://pic.lijiakaijun.cyou/light.webp
  dark: https://pic.lijiakaijun.cyou/dark.webp

footer:
  live_time:
    enable: true
    prefix: ä¸ç»æ„é—´ï¼Œæœ¬ç«™å·²ç»è¿è¡Œäº†
    suffix: (â—'â—¡'â—)<br><a href="https://icp.gov.moe" target="_blank">èŒICPå¤‡</a><a href="https://icp.gov.moe/?keyword=20215956" target="_blank"> 20215956å·</a>
    start_time: "2019-09-14T10:08:00"
  custom_text: <a href="https://feeds.pub/feed/https%3A%2F%2Fblog.lijiakaijun.cyou%2Fatom.xml"><img src="https://img.shields.io/badge/dynamic/json?label=follow&query=%24.data.feed.followerCount&url=https%3A%2F%2Fapi.feeds.pub%2Fgraphql%3Fquery%3Dquery%2520feed%28%2524id%253A%2520String%21%29%257B%2520feed%28id%253A%2520%2524id%29%2520%257B%2520followerCount%2520%257D%2520%257D%26variables%3D%257B%2522id%2522%253A%2520%2522https%3A%2F%2Fblog.lijiakaijun.cyou%2Fatom.xml%2522%257D%26operationName%3Dfeed&style=social&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEUAAABFCAYAAAAcjSspAAAACXBIWXMAAAInAAACJwG+ElQIAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAASkSURBVHgB7Ztdcts2EMf/oDyeNO5MnBOUN4hzAtNvrZ0H8QSimwPEPoHlE9g5gZkTSJ46mU77YPYEVd/6yN5AnWkzrVNxuxAhN3UA0YL46eA3Y30AkDT8c7FY7MKAw+FwlIfAAyAafe2rl/w8m8bhjxOsQedEiUbBNrAVeQLPCBTwJfiaYROiWRiH36ewYAMdIBfiUV+I3oDfBrKN5j3Ge7rDYy/4eQ8WtFoUOS08zxsQiSN+u73ap7EDS1opCosR8J0+4ZcBEWyZwpJWiRKN9tnsxRnUFFkHIjqFJa1wtNJneN7WCVvFEexgqyD+E1MBkWaUXcbhuxiWNC7Ky8sXrzKiIVbzGVO2hDeANwb+mMRhYj1VdDQmytw6xJcXvKz2V/hYwk73NA6vElRII6Io3zHCPNgqhK1CvGaLOC/bIkzU7mij0TccbwgZQxRNl9rFWFCrpby8PBhkhLhoHPsLFuP9sG4xFtQmioo9rguGcXgujqv2GUX0UAMyMmVBpA8xThllHYdx+MOvaJhafIqyEN/Qzb7DY+v4LkZLqFwUFYf4hm4Zb+yxIGtt9cumUp+ipo3RSliQ5xx5tkoQiYdK8QIYBcFxGwWRVCoKxyMnhi4Ozd+eo6VUJopKEfq6PqKbQ7SYCh3txs4iP3aHqRCbZ4fjA16eSS3RIp0/CkyyjH4BssQ2lVgGFYqS7Rj8uBQiyF/e9vvygf0MB3iyrYdvxwdxRrPTJsSpZPrkq47YxRqwjUW8cv0sN4+omdJFkXGJvBiUkD1jtlnc649KGLVQ2vTJ8yOPzzhQi1AuPN08mZGzzcqtTCmWIgURYuuaICJUAFvLADWydkS7EAT3LClwFPsT3wuOUbIU2OTUwI20BOl85WrEuRYM9J/782lnkkwq4XxvZ8h3/auL/tXY0D0+HO/v6qp+vc3HT7BG2WIV1po+vDJEFhl4P6/4mRDaC5/dfHiKmlhLlCVhvIw5ONtOqb73i0DXGo36UiyD1X1IURPWokgrgXn3+5r3NlHuPzQ/anCcPe8fk0NN60xNWouyxEr4At6pKSUS3QBepYK7U0jGIqr+oxmPBDViJYqKMn1dH+dYP9rsbUqHqrvD84rgf993m3fR+xoSb1AjVktyNDo44qXzTNM1uei/ff7/sfvnbFWvdN8jRG4ZBacKEv5OqyMVtlgtyewTdkmzAybKNHc045ikpxWFxRiiAKJZ7WkGq+lDt1v+u/Q+yaTJXW5e1LL4nXl2rjO7ZFMi+m/DCrEx5IcUq/zCvGbcTHbOUhTh61pNB/DicMxZ+5n0CynuQW4hV0M0xMqiqABLx9I4Ip9Gsz1ejsdLhiV5hr/Z/K2Fo/1r21BYLAyulH8Io9GLgB2wLLQ/ExzWZ5T9Js+aNF0uXdDI8S518Qlaio1P8Q3tKR4IFRfDuokTRYONKKmh3ccDwVmKBieKBieKBgtRHpmCtKLTjp1hZVHkPsbQ9fmK8jlgK4rWWpaXLrqDbT5FK4oqWHUeN300OFE0OFE02KYjU13r7Ob973gA2GXziY5xZwXKE83N/NdF2VifT8mPXHlHXAN6knEFry2pRIfD4XA4usm//qauBcoh1b8AAAAASUVORK5CYII=" width="84" height="19.9" alt="Follow on Feeds Pub"/></a>

# æœç´¢ç›¸å…³

engine_search:
  enable: false

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia
algolia_search:
  enable: false
  # ...

local_search:
  enable: true

# ç½‘ç«™ç»Ÿè®¡/å¹¿å‘Šç›¸å…³

google_analytics:
  enable: true
  id: UA-147974252-3

google_adsense:
  enable: false
  client: 

baidu_push: false

google_tagmanager:
  enable: false
  id: 


# ç¼–è¾‘

post_edit:
  enable: true
  url: https://github.com/lijiajunljj/lijiakaijun-blog/tree/main/source/

girls:
  enable: true

# é¡µé¢é“¾æ¥ã€å¯¼èˆª

pages:
  - name: å‹~é“¾~
    url: /links
    icon: ri:genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls
    icon: ri:women-line
    color: hotpink

menu:
  home:
    path: /
    icon: ri:home-4-line
  list:
    - type: archives
      path: /archives
  custom:
    title: ç•™è¨€æ¿
    path: /contact
    icon: ri:clipboard-line

cursor:
  enable: true


wordcount:
  enable: true

# ä¸€è¨€

say:
  enable: true
  api: /files/onetext-blog.json
  hitokoto:
    enable: false
    api: https://v1.hitokoto.cn

# ç¤¾äº¤
social:
  - name: ä¸»é¡µ
    link: https://lijiakaijun.cyou
    icon: ri:home-line
    color: "50D7D2"
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: ri:rss-line
    color: orange
  - name: bilibili
    link: https://space.bilibili.com/480198701
    icon: ri:bilibili-line
    color: "#FF8EB3"
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=1509875152
    icon: ri:netease-cloud-music-line
    color: "#C10D0C"
  - name: GitHub
    link: https://github.com/lijiakaijun
    icon: ri:github-line
    color: "#95A4A6"
  - name: Twitter
    link: https://twitter.com/lijia_ver6
    icon: ri:twitter-line
    color: "#1da1f2"
  - name: Telegramé¢‘é“
    link: https://t.me/lijiakaijun
    icon: ri:telegram-line
    color: "#0088CC"
  - name: E-Mail
    link: mailto:wwln@lijiakaijun.cyou
    icon: ri:mail-line
    color: "#8E71C1"

# æ‚é¡¹

mourn:
  enable: true
  days:
    - "2-15"
    - "4-4"

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false

# cdn

vendors:
  # ä»¥ '/' ç»“å°¾
  host: 'https://fastly.jsdelivr.net/npm/'