# UI
mode: auto

# ç½‘ç«™åŸºæœ¬é…ç½®

avatar:
  enable: true
  url: /me.webp
  opacity: 1
  status:
    enable: false
    emoji: ğŸŒ‘
    message: Looking for dawn.

favicon: /favicon.ico

pjax:
  enable: true

# å…¬å‘Š

notice:
  enable: true
  content: åŸŸåè¿™å‡ ä¸ªæœˆå¯èƒ½ä¼šæœ‰å˜åŠ¨ï¼Œä½†ç»­æœŸè¿˜æ˜¯ä¼šç»­æœŸçš„ï¼ˆ

# èµèµç 

reward:
  enable: false
  comment: æˆ‘å¾ˆå¯çˆ±ï¼Œè¯·ç»™æˆ‘é’±
  methods:
    - name: æ”¯ä»˜å®
      path: 
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: QQ æ”¯ä»˜
      path: 
      color: "#12B7F5"
      icon: icon-qq-line
    - name: å¾®ä¿¡æ”¯ä»˜
      path: 
      color: "#2DC100"
      icon: icon-wechat-pay-line

# è¯„è®º

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - ä¸€èˆ¬æ¥è¯´éƒ½æ˜¯å¼ºåˆ¶ä½ å†™é‚®ç®±åœ°å€ä»¥ä¾¿äºæ”¶åˆ°å›å¤é€šçŸ¥

waline:
  enable: true
  serverURL: https://pl-lijiakaijun.vercel.app
  visitor: true
  comment: true
  emoji:
    - https://cdn.jsdelivr.net/gh/walinejs/emojis@latest/bilibili/
    - https://pic.lijiakaijun.cyou/emote/reci
    - https://pic.lijiakaijun.cyou/emote/kano
    - https://pic.lijiakaijun.cyou/emote/qinai
    - https://pic.lijiakaijun.cyou/emote/orange
    - https://pic.lijiakaijun.cyou/emote/mea
  locale:
    placeholder: é˜¿å·´é˜¿å·´
  requiredMeta: ['nick', 'mail']

github_issues:
  enable: false

github_discussions:
  enable: false

disqusjs:
  enable: false
  shortname: 
  apikey: 

# https://github.com/laymonage/giscus
giscus:
  enable: false
  repo: YunYouJun/yunyoujun.github.io
  repo-id:
  category-id:
  mapping: pathname
  reactions-enabled: 1
  emit-metadata: 0
  theme: light

# é¡µå¤´ä¸é¡µå°¾

banner:
  enable: true
  title: 
    - lijia
    - kaijun
  border: true
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

bg_image:
  enable: true
  url: https://pic.lijiakaijun.cyou/light.webp
  dark: https://pic.lijiakaijun.cyou/dark.webp

footer:
  live_time:
    enable: true
    prefix: ä¸ç»æ„é—´ï¼Œæœ¬ç«™å·²ç»è¿è¡Œäº†
    suffix: (â—'â—¡'â—)
    start_time: "2019-09-14T10:08:00"
  custom_text: <a href="https://icp.gov.moe" target="_blank">èŒICPå¤‡</a><a href="https://icp.gov.moe/?keyword=20215956" target="_blank"> 20215956å·</a><!-- Cloudflare Web Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js?token=f7e91cb847eb445c9d6804fae5889cb6'></script><!-- End Cloudflare Web Analytics -->

# æœç´¢ç›¸å…³

engine_search:
  enable: false

# If you want to use it, you need config algolia appID in _config.yml!!!
# https://github.com/oncletom/hexo-algolia
algolia_search:
  enable: false
  # ...

local_search:
  enable: true

# ç½‘ç«™ç»Ÿè®¡/å¹¿å‘Šç›¸å…³

google_analytics:
  enable: true
  id: UA-147974252-3

google_adsense:
  enable: false
  client: 

baidu_push: false

google_tagmanager:
  enable: false
  id: 


# ç¼–è¾‘

post_edit:
  enable: true
  url: https://github.com/lijiajunljj/lijiakaijun-blog/tree/source/

girls:
  enable: true

# é¡µé¢é“¾æ¥ã€å¯¼èˆª

pages:
  - name: å‹~é“¾~
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: å–œæ¬¢çš„å¥³å­©å­
    url: /girls/
    icon: icon-women-line
    color: hotpink

menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
  custom:
    title: ç•™è¨€æ¿
    path: /contact
    icon: icon-clipboard-line

cursor:
  enable: true


wordcount:
  enable: true

# ä¸€è¨€

say:
  enable: true
  api: /files/onetext-blog.json
  hitokoto:
    enable: false
    api: https://v1.hitokoto.cn

# ç¤¾äº¤
social:
  - name: RSS
    # set rss in your root config
    # https://github.com/hexojs/hexo-generator-feed
    link: /atom.xml # config.feed.path
    icon: icon-rss-line
    color: orange
  - name: ç½‘æ˜“äº‘éŸ³ä¹
    link: https://music.163.com/#/user/home?id=1509875152
    icon: icon-netease-cloud-music-line
    color: "#C10D0C"
  - name: bilibili
    link: https://space.bilibili.com/480198701
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: GitHub
    link: https://github.com/lijiajunljj
    icon: icon-github-line
    color: "#181717"
  - name: Twitter
    link: https://twitter.com/Kw_sing_Ironi
    icon: icon-twitter-line
    color: "#1da1f2"
  - name: Telegramé¢‘é“
    link: https://t.me/lijiakaijun
    icon: icon-telegram-line
    color: "#0088CC"
  - name: E-Mail
    link: mailto:wwln@lijiakaijun.cyou
    icon: icon-mail-line
    color: "#8E71C1"

# æ‚é¡¹

mourn:
  enable: false
  days:
    - "4-4"

creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false
